<% postgres_name = ENV['POSTGRES_NAME'] || 'NO_POSTGRES_NAME_SET' %>
<% username = postgres_name.sub(/\/.*\//, '') %>

default: &default
  adapter: postgresql
  username: <%= username %>
  host:     <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port:     <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development
test:
  <<: *default
  database: test
production:
  <<: *default