
default: &default
  adapter: postgresql
  username: sample_app
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development
test:
  <<: *default
  database: test
production:
  <<: *default
  database: production
